Rscript plot_trace.R demo5_trace_0
Rscript plot_trace.R demo5_trace_1
Rscript plot_trace.R demo5_trace_2
Rscript plot_trace.R demo5_trace_3
Rscript plot_trace.R demo5_trace_4
Rscript plot_trace.R demo5_trace_5
Rscript plot_trace.R demo5_trace_6
Rscript plot_trace.R demo5_trace_7
Rscript plot_trace.R demo5_trace_8
Rscript plot_trace.R demo5_trace_9
Rscript plot_trace.R demo_trace_0
Rscript plot_trace.R demo_trace_1
Rscript plot_trace.R demo_trace_2
Rscript plot_trace.R demo_trace_3
Rscript plot_trace.R demo_trace_4
Rscript plot_trace.R demo_trace_5
Rscript plot_trace.R demo_trace_6
Rscript plot_trace.R demo_trace_7
Rscript plot_trace.R demo_trace_8
Rscript plot_trace.R demo_trace_9
Rscript plot_trace.R improved5_trace_0
Rscript plot_trace.R improved5_trace_1
Rscript plot_trace.R improved5_trace_2
Rscript plot_trace.R improved5_trace_3
Rscript plot_trace.R improved5_trace_4
Rscript plot_trace.R improved5_trace_5
Rscript plot_trace.R improved5_trace_6
Rscript plot_trace.R improved5_trace_7
Rscript plot_trace.R improved5_trace_8
Rscript plot_trace.R improved5_trace_9
Rscript plot_trace.R improved_trace_0
Rscript plot_trace.R improved_trace_1
Rscript plot_trace.R improved_trace_2
Rscript plot_trace.R improved_trace_3
Rscript plot_trace.R improved_trace_4
Rscript plot_trace.R improved_trace_5
Rscript plot_trace.R improved_trace_6
Rscript plot_trace.R improved_trace_7
Rscript plot_trace.R improved_trace_8
Rscript plot_trace.R improved_trace_9
